version: '3'
services:
  todo-app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    command: 
      - sh
      - -c
      - "node ace migration:run --force && npm start"
