version: '3'
services:
  todo-app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    depends_on:
      - migration-runner
    command: ["npm", "start"]

  migration-runner:
    build: .
    environment:
      - NODE_ENV=development
    entrypoint: ["node", "ace", "migration:run"]
