version: '3'
services:
  todo-app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    command: 
      - npm
      - start
    volumes:
      - ./migrations:/migrations
    entrypoint:
      - sh
      - -c
      - |
        npm run migrate
        npm start
